{% set name = "conda-tree" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rvalieris/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9479a66a404c95367dc2573e650883f162d4e8b772c8204bbd8a36e3b74c5018

build:
  number: 2
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - conda-tree = conda_tree:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - networkx
    - conda
    - colorama

test:
  commands:
    - conda-tree -h

about:
  home: https://github.com/rvalieris/conda-tree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: conda dependency tree helper
  dev_url: https://github.com/rvalieris/conda-tree
  doc_url: https://github.com/rvalieris/conda-tree

extra:
  recipe-maintainers:
    - xylar
    - rvalieris
