schema_version: 1

context:
  name: conda-tree
  version: "1.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/rvalieris/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: e68481c65d7d248a3b87881df6bb88547799499bcac76655a99937923a431fdc

build:
  number: 1
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv
  python:
    entry_points:
      - conda-tree = conda_tree:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - networkx
    - conda
    - colorama

tests:
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - conda-tree -h
      - pip check

about:
  license: MIT
  license_file: LICENSE
  summary: conda dependency tree helper
  homepage: https://github.com/rvalieris/conda-tree
  repository: https://github.com/rvalieris/conda-tree
  documentation: https://github.com/rvalieris/conda-tree

extra:
  recipe-maintainers:
    - xylar
    - rvalieris
